# Data Cleaning

## Data Cleaning_ Visitor profile

In [1]:
import pandas as pd

In [3]:
visitors = pd.read_csv("../source/visitors.csv")
visitors_answers = pd.read_csv("../source/visitors_answers.csv")
visitors_questions = pd.read_csv("../source/visitors_questions.csv")

In [5]:
visitors.head()

,email,gender,id,data
0,emilija+100_L8gA@bss.mk,F,67b70a9f2d21f543a1096602,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
1,aleksandar.dimkov+mitt1_n5eA@bss.com.mk,M,67ada1ee197e604dd2722d1b,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
2,daniela.p+150_YhiF@bss.com.mk,F,67b44fef197e604dd2722d3d,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
3,tanja+182_jiPa@bss.com.mk,F,67b45018197e604dd2722d3e,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."
4,aleksandar.dimkov+mitt10_V0iB@bss.com.mk,M,67b5f1392d21f543a10965f1,"[{ ""stepId"" : ""5c8a78336d41a10da4f730ef"", ""que..."

In [7]:
visitors_answers.head()

,id,answer,questionId
0,5c8a78336d41a10da4f73103,Personal interest,5c8a78336d41a10da4f730fe
1,5c8a78336d41a10da4f73100,To obtain general information,5c8a78336d41a10da4f730fe
2,5c8a78336d41a10da4f730ff,To source products and services,5c8a78336d41a10da4f730fe
3,5c8a78336d41a10da4f73101,To promote products and services,5c8a78336d41a10da4f730fe
4,5c8a78336d41a10da4f73102,Educational purposes,5c8a78336d41a10da4f730fe

In [9]:
visitors_questions.head()

,id,questionTypeId,stepId,question
0,5c8a78336d41a10da4f730fe,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f730fd,Reason for Attending the Event
1,5c8a78336d41a10da4f73253,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f73252,Please indicate your company's main area of bu...
2,5c8a78336d41a10da4f7336d,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f7336c,What role do you play in the purchasing decisi...
3,5c8a78336d41a10da4f73372,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f7336c,What is your company's annual purchasing budget?
4,5c8a78336d41a10da4f73227,5bf7c399b82beb7a182cc3de,5c8a78336d41a10da4f73225,Which of the following best describes your job...

In [11]:

print("Visitors shape:", visitors.shape)
print("Visitors answers shape:", visitors_answers.shape)
print("Visitors questions shape:", visitors_questions.shape)

Visitors shape: (100, 4)
Visitors answers shape: (43, 3)
Visitors questions shape: (5, 4)

In [13]:
print("Visitors columns:", visitors.columns)
print("Visitors answers columns:",visitors_answers.columns)
print("Visitors questions columns:",visitors_questions.columns)

Visitors columns: Index(['email', 'gender', 'id', 'data'], dtype='object')
Visitors answers columns: Index(['id', 'answer', 'questionId'], dtype='object')
Visitors questions columns: Index(['id', 'questionTypeId', 'stepId', 'question'], dtype='object')

In [16]:
# Clean visitors data
print("\nBefore cleaning:")
print("Null values:\n", visitors.isnull().sum())
print("Duplicate emails:", visitors.duplicated('email').sum())

visitors.drop_duplicates(subset='email', inplace=True)
visitors['gender'] = visitors['gender'].fillna('Not Specified')

print("\nAfter cleaning:")
print("New shape:", visitors.shape)
print("Null values:\n", visitors.isnull().sum())

Before cleaning:
Null values:
 email     0
gender    0
id        0
data      0
dtype: int64
Duplicate emails: 0

After cleaning:
New shape: (100, 4)
Null values:
 email     0
gender    0
id        0
data      0
dtype: int64

In [18]:
visitors_clean = visitors[['email', 'gender', 'id', 'data']].copy()

# Lowercase emails
emails = visitors_clean['email'].str.lower()

# Remove "+..." in local part
emails = emails.str.replace(r'\+.*?(?=@)', '', regex=True)

# Fix repeated domain endings like ".com.com"
emails = emails.str.replace(r'(\.com|\.net|\.org)(\1)+$', r'\1', regex=True)

# Remove emails without '@'
emails = emails.where(emails.str.contains('@'))

visitors_clean['email'] = emails

print("\n=== Cleaned Visitors ===")
print(visitors_clean[['email', 'gender', 'id']].head(2))

=== Cleaned Visitors ===
                          email gender                        id
0                emilija@bss.mk      F  67b70a9f2d21f543a1096602
1  aleksandar.dimkov@bss.com.mk      M  67ada1ee197e604dd2722d1b

In [20]:
print("First visitor's raw data:")
print(visitors['data'].iloc[0])

First visitor's raw data:
[{ "stepId" : "5c8a78336d41a10da4f730ef", "questionId" : "5c8a78336d41a10da4f730f0", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f730f2", "answerTypeId" : "Answer" }, { "stepId" : "6507da8d9e117216630ef7ed", "questionId" : "6507de7e9e117216630ef7f2", "answerValue" : "emilija+100_L8gA@bss.mk", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "6507dfbb9e117216630ef7f3", "questionId" : "6507e0219e117216630ef7f5", "answerValue" : "3138", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733d8", "answerValue" : "Eme", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733e2", "answerValue" : "Jankova", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733cf", "answerValue" : "Emilija", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f733ce", "questionId" : "5c8a78336d41a10da4f733d9", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f733de", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f4", "answerValue" : "Russia", "answerId" : "5c8a78346d41a10da4f7348e", "answerTypeId" : "Country" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f4", "answerValue" : "Komi Republic", "answerId" : "5c8a78346d41a10da4f734a6", "answerTypeId" : "Region" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f5", "answerValue" : "Komi", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730fb", "answerValue" : "Ivo Ribar Lola 54a", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730fc", "answerValue" : "78877665", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5c8a78336d41a10da4f730f7", "answerValue" : true, "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730f3", "questionId" : "5d7a4eb1bd2e7e3e64f57a25", "answerValue" : true, "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730fd", "questionId" : "5c8a78336d41a10da4f730fe", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73100", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730fd", "questionId" : "5c8a78336d41a10da4f73104", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7315f", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f730fd", "questionId" : "5c8a78336d41a10da4f73104", "answerValue" : "", "answerId" : "67acad10197e604dd2722d08", "answerTypeId" : "Answer" }, { "stepId" : "65a51b5a097d28c29bcb7403", "questionId" : "65a51b7a097d28c29bcb7404", "answerValue" : "", "answerId" : "65a51b87097d28c29bcb7405", "answerTypeId" : "Answer" }, { "stepId" : "65a51b5a097d28c29bcb7403", "questionId" : "65a51b7a097d28c29bcb7404", "answerValue" : "", "answerId" : "65a51b9a097d28c29bcb7406", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f7324a", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7324e", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f73227", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73244", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f73226", "answerValue" : "BSS", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73225", "questionId" : "5c8a78336d41a10da4f73250", "answerValue" : "tester", "answerId" : "", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73253", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73291", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f7334e", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7334f", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f7334e", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73350", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73326", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73334", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73358", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73359", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73358", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7335b", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f73358", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7335c", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f73252", "questionId" : "5c8a78336d41a10da4f732ed", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f732ef", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f7336c", "questionId" : "5c8a78336d41a10da4f7336d", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f73371", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f7337a", "questionId" : "5c8a78336d41a10da4f7337b", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7337c", "answerTypeId" : "Answer" }, { "stepId" : "5c8a78336d41a10da4f7337a", "questionId" : "5c8a78336d41a10da4f7337e", "answerValue" : "", "answerId" : "5c8a78336d41a10da4f7337f", "answerTypeId" : "Answer" }]

In [22]:
def extract_answers(json_str):
    try:
        data = json.loads(json_str) if isinstance(json_str, str) else json_str
    except:
        try:
            data = literal_eval(json_str.replace("'", '"'))
        except:
            return []
    return [{
        'questionId': item.get('questionId'),
        'answerValue': str(item.get('answerValue', '')).strip(),
        'answerId': item.get('answerId'),
        'answerType': item.get('answerTypeId', 'TEXT')
    } for item in data if isinstance(item, dict)]

answers_expanded = []
for _, row in visitors_clean.iterrows():
    for answer in extract_answers(row['data']):
        answer['visitor_id'] = row['id']
        answer['email'] = row['email']
        answer['gender'] = row['gender']
        answers_expanded.append(answer)

print("\n=== Expanded Answers ===")
print(pd.DataFrame(answers_expanded[:3]))

=== Expanded Answers ===
                 questionId              answerValue  \
0  5c8a78336d41a10da4f730f0
1  6507de7e9e117216630ef7f2  emilija+100_L8gA@bss.mk
2  6507e0219e117216630ef7f5                     3138

                   answerId answerType                visitor_id  \
0  5c8a78336d41a10da4f730f2     Answer  67b70a9f2d21f543a1096602
1                               Answer  67b70a9f2d21f543a1096602
2                               Answer  67b70a9f2d21f543a1096602

            email gender
0  emilija@bss.mk      F
1  emilija@bss.mk      F
2  emilija@bss.mk      F

In [24]:
questions_ref = visitors_questions[['id', 'question', 'stepId', 'questionTypeId']]
answers_ref = visitors_answers[['id', 'answer', 'questionId']]

print("\n=== Reference Data ===")
print("Questions:\n", questions_ref.head(2))
print("\nAnswers:\n", answers_ref.head(2))

=== Reference Data ===
Questions:
                          id  \
0  5c8a78336d41a10da4f730fe
1  5c8a78336d41a10da4f73253

                                            question  \
0                     Reason for Attending the Event
1  Please indicate your company's main area of bu...

                     stepId            questionTypeId
0  5c8a78336d41a10da4f730fd  5bf7c399b82beb7a182cc3de
1  5c8a78336d41a10da4f73252  5bf7c399b82beb7a182cc3de

Answers:
                          id                         answer  \
0  5c8a78336d41a10da4f73103              Personal interest
1  5c8a78336d41a10da4f73100  To obtain general information

                 questionId
0  5c8a78336d41a10da4f730fe
1  5c8a78336d41a10da4f730fe

In [26]:
final_data = (
    pd.DataFrame(answers_expanded)
    .merge(questions_ref.rename(columns={'id': 'questionId'}), on='questionId')
    .merge(answers_ref.rename(columns={'id': 'answerId'}), on=['answerId', 'questionId'], how='left')
)

final_data['final_answer'] = final_data['answer'].combine_first(final_data['answerValue'])

print("\n=== Final Merged Data ===")
print(final_data[['visitor_id', 'question', 'final_answer', 'answerType']].head(3))

=== Final Merged Data ===
                 visitor_id  \
0  67b70a9f2d21f543a1096602
1  67b70a9f2d21f543a1096602
2  67b70a9f2d21f543a1096602

                                            question  \
0                     Reason for Attending the Event
1  Which of the following best describes your job...
2  Please indicate your company's main area of bu...

                    final_answer answerType
0  To obtain general information     Answer
1                          Media     Answer
2                   Travel Agent     Answer

In [28]:
output_cols = [
    'visitor_id', 'email', 'gender',
    'stepId', 'questionTypeId', 'questionId',
    'question', 'answerId', 'final_answer', 'answerType'
]

final_output = final_data[output_cols]

print("\n=== Final Output Structure ===")
print(final_output.head(2))
print("\nShape:", final_output.shape)

=== Final Output Structure ===
                 visitor_id           email gender                    stepId  \
0  67b70a9f2d21f543a1096602  emilija@bss.mk      F  5c8a78336d41a10da4f730fd
1  67b70a9f2d21f543a1096602  emilija@bss.mk      F  5c8a78336d41a10da4f73225

             questionTypeId                questionId  \
0  5bf7c399b82beb7a182cc3de  5c8a78336d41a10da4f730fe
1  5bf7c399b82beb7a182cc3de  5c8a78336d41a10da4f73227

                                            question  \
0                     Reason for Attending the Event
1  Which of the following best describes your job...

                   answerId                   final_answer answerType
0  5c8a78336d41a10da4f73100  To obtain general information     Answer
1  5c8a78336d41a10da4f73244                          Media     Answer

Shape: (391, 10)

In [30]:

analysis_ready = (
    final_data
    .drop(columns=['stepId', 'questionTypeId', 'questionId', 'answerId'])
    .rename(columns={'final_answer': 'answer'})
    [['visitor_id', 'email', 'gender', 'question', 'answer', 'answerType']]
)

In [32]:
analysis_ready

,visitor_id,email,gender,question,answer,answer,answerType
0,67b70a9f2d21f543a1096602,emilija@bss.mk,F,Reason for Attending the Event,To obtain general information,To obtain general information,Answer
1,67b70a9f2d21f543a1096602,emilija@bss.mk,F,Which of the following best describes your job...,Media,Media,Answer
2,67b70a9f2d21f543a1096602,emilija@bss.mk,F,Please indicate your company's main area of bu...,Travel Agent,Travel Agent,Answer
3,67b70a9f2d21f543a1096602,emilija@bss.mk,F,What role do you play in the purchasing decisi...,No influence,No influence,Answer
4,67ada1ee197e604dd2722d1b,aleksandar.dimkov@bss.com.mk,M,Reason for Attending the Event,To source products and services,To source products and services,Answer
...,...,...,...,...,...,...,...
386,uud1nluegdqmisnfzpg75iqg,daniela.p@bss.com.mk,M,What role do you play in the purchasing decisi...,Advisory role,Advisory role,Answer
387,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,Reason for Attending the Event,To obtain general information,To obtain general information,Answer
388,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,Which of the following best describes your job...,Guided tour services,Guided tour services,Answer
389,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,Please indicate your company's main area of bu...,Travel Agent,Travel Agent,Answer
390,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,What role do you play in the purchasing decisi...,Advisory role,Advisory role,Answer

In [43]:
analysis_ready = analysis_ready.loc[:, ~analysis_ready.columns.duplicated()]

In [49]:
analysis_ready.loc[:, 'answerType'] = analysis_ready['answerType'].fillna("No answer")
analysis_ready.drop_duplicates(inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_18004\2221370406.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  analysis_ready.drop_duplicates(inplace=True)

In [51]:
analysis_ready

,visitor_id,email,gender,question,answer,answerType
0,67b70a9f2d21f543a1096602,emilijabss.mk,FEMALE,Reason for Attending the Event,To obtain general information,Answer
1,67b70a9f2d21f543a1096602,emilijabss.mk,FEMALE,Which of the following best describes your job...,Media,Answer
2,67b70a9f2d21f543a1096602,emilijabss.mk,FEMALE,Please indicate your company's main area of bu...,Travel Agent,Answer
3,67b70a9f2d21f543a1096602,emilijabss.mk,FEMALE,What role do you play in the purchasing decisi...,No influence,Answer
4,67ada1ee197e604dd2722d1b,aleksandar.dimkovbss.com.mk,MALE,Reason for Attending the Event,To source products and services,Answer
...,...,...,...,...,...,...
386,uud1nluegdqmisnfzpg75iqg,daniela.pbss.com.mk,MALE,What role do you play in the purchasing decisi...,Advisory role,Answer
387,mv0j9yovwhgmtif9l1naciko,daniela.pbss.com.mk,MALE,Reason for Attending the Event,To obtain general information,Answer
388,mv0j9yovwhgmtif9l1naciko,daniela.pbss.com.mk,MALE,Which of the following best describes your job...,Guided tour services,Answer
389,mv0j9yovwhgmtif9l1naciko,daniela.pbss.com.mk,MALE,Please indicate your company's main area of bu...,Travel Agent,Answer
390,mv0j9yovwhgmtif9l1naciko,daniela.pbss.com.mk,MALE,What role do you play in the purchasing decisi...,Advisory role,Answer

In [53]:
# Drop the 'answerType' column
analysis_ready.drop(columns=['answerType'], inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_18004\3668956367.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  analysis_ready.drop(columns=['answerType'], inplace=True)

In [34]:
analysis_ready

,visitor_id,email,gender,question,answer,answer,answerType
0,67b70a9f2d21f543a1096602,emilija@bss.mk,F,Reason for Attending the Event,To obtain general information,To obtain general information,Answer
1,67b70a9f2d21f543a1096602,emilija@bss.mk,F,Which of the following best describes your job...,Media,Media,Answer
2,67b70a9f2d21f543a1096602,emilija@bss.mk,F,Please indicate your company's main area of bu...,Travel Agent,Travel Agent,Answer
3,67b70a9f2d21f543a1096602,emilija@bss.mk,F,What role do you play in the purchasing decisi...,No influence,No influence,Answer
4,67ada1ee197e604dd2722d1b,aleksandar.dimkov@bss.com.mk,M,Reason for Attending the Event,To source products and services,To source products and services,Answer
...,...,...,...,...,...,...,...
386,uud1nluegdqmisnfzpg75iqg,daniela.p@bss.com.mk,M,What role do you play in the purchasing decisi...,Advisory role,Advisory role,Answer
387,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,Reason for Attending the Event,To obtain general information,To obtain general information,Answer
388,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,Which of the following best describes your job...,Guided tour services,Guided tour services,Answer
389,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,Please indicate your company's main area of bu...,Travel Agent,Travel Agent,Answer
390,mv0j9yovwhgmtif9l1naciko,daniela.p@bss.com.mk,M,What role do you play in the purchasing decisi...,Advisory role,Advisory role,Answer

In [36]:
analysis_ready.to_csv("final_analysis_data_visitors.csv", index=False)
print("\nData successfully saved!")

Data successfully saved!

## Data Cleaning_ Exhibitor profile

In [38]:
#datasets
exhibitor_categories = pd.read_csv("../source/exhibitor_categories.csv")
exhibitors = pd.read_csv("../source/exhibitors.csv")

In [40]:
exhibitor_categories.head()

   categoryId                        categoryName
0       52271           1. Accomodation providers
1       52272       1.1 Hotel / Hotel chain / Inn
2       52273  1.2 Apartments / Residential hotel
3       52274                  1.3 Hostel / Motel
4       52275                  1.4 Boarding house

In [42]:
exhibitors.head()

   exhibitorid                    Name                       MainCategories
0        90556          Turkey Travels                    52276|52280|52281
1        92462  Russian Travel Company  52273|52283|52289|52291|52298|52302
2        92491   Indian Travel Company                    52273|52274|52281
3        92492            Asia Tourism              52272|52276|52352|52358
4        92493     SriLanka Adventures                    52296|52327|52352

In [44]:
# Check for missing or duplicate values
exhibitor_categories.isnull().sum()
exhibitor_categories.duplicated().sum()

0

In [46]:
exhibitor_categories['categoryName'] = exhibitor_categories['categoryName'].str.strip()

In [48]:
# Step 1: Split the pipe-separated string into lists
exhibitors['MainCategories'] = exhibitors['MainCategories'].str.split('|')

# Step 2: list into multiple rows
exhibitor_cleaned = exhibitors.explode('MainCategories')

# Step 3: Convert category IDs to integers for merging
exhibitor_cleaned['MainCategories'] = exhibitor_cleaned['MainCategories'].astype(int)

In [50]:
exhibitor_cleaned.head(2)

   exhibitorid            Name  MainCategories
0        90556  Turkey Travels           52276
0        90556  Turkey Travels           52280

In [52]:
exhibitor_with_categories = exhibitor_cleaned.merge(
    exhibitor_categories,
    left_on='MainCategories',
    right_on='categoryId',
    how='left'
)

In [54]:
exhibitor_final = exhibitor_with_categories[[
    'exhibitorid', 'Name', 'MainCategories', 'categoryName'
]].rename(columns={
    'MainCategories': 'categoryId'
})

In [56]:
exhibitor_final.head()

,exhibitorid,Name,categoryId,categoryName
0,90556,Turkey Travels,52276,1.5 Resort hotel
1,90556,Turkey Travels,52280,2.1 Inbound tour operator
2,90556,Turkey Travels,52281,2.2 Outbound tour operator
3,92462,Russian Travel Company,52273,1.2 Apartments / Residential hotel
4,92462,Russian Travel Company,52283,2.4 Mass market tour operators

In [58]:
exhibitor_final.to_csv("exhibitor_final.csv", index=False)

In [60]:
exhibitor_final.shape

(183, 4)